name: My First Workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello there, this is my first workflow"
      - name: Print goodbye
        run: echo "Job Completed"
