name: My First Workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: | 
            echo "Hello there, this is my first workflow"
            echo "Hello there, this is my first workflow 2"
      - name: Print goodbye
        run: echo "Job Completed"
